### ISSUE TITLE
5.0.0 roadmap

### ISSUE THREAD

**Issue by bzah** [cerfacs-globc/icclim#101]
We are very close to releasing a 5.0.0 version of icclim but a few points should be considered before the release.
These are suggestions not an exact roadmap to follow.

### ~Clean 4.x.x opened issues~

~We have a few (10) trailing issues from 4.x.x versions of icclim.
We should consider reviewing each one of them and close those which are now irrelevant.
I suggest to keep feature request if there are any. 
For bugs, we should probably redirect users to the 5.0.0 version (once it is released).~

### Improve documentation
- ~We should add an article explaining why icclim 5.0.0 exist now and how it differs from xclim.: #107~
- We might want to add an article comparing the results of icclim and climpact, make sure we don't have a license issue with that because climpact is in GPL 3. 
- Add dev documentation articles to explain:
  - how to contribute to icclim 
  - ~how to release icclim~
  - ~what does our CI do (it is split between github actions, pre-commit ci and readthedoc PR hook)~
- ~We should consider adding a PR template with a check list (xclim has a good example of this)~
- ~We should consider adding an issue template to help user describe their issue (and ease their reading for ourselves)~
- ~Update tags on github with "xclim", "xarray", "dask"~
- ~Add a "how to" article for the Dask usage.~
- ~Add a comprehensive table of the precise and exact definitions of each climate index. I (Christian) thought this has always been missing, even though there is the pdf available for example for ECA&D. This will also help to be properly referenced in google for users to find the package.~
- Bring examples up-to-date with new version (for example "index TG90p with callback" may not be relevant anymore).
- ~Reference the notebooks developed for C4I.~
- have a Gallery of a few examples using those notebooks.

### Run a campaign on windows
~All dev have been made on unix like environment and we already have a bug on windows #108 .
It would be good to run a few tests on windows before releasing.~

### Publish to conda forge
We already have requests to publish icclim to conda forge.

### A pretty logo
It would be nice to have a logo for icclim.
It would make sense to display it on readthedoc and on the presentations we do.

### Unit tests
For now icclim has very few unit tests.
We should consider setting a minimal coverage goal and display the actual coverage on pull requests and our github home page.

ping: @pagecp

**Comment by pagecp** [comment]
I agree with all what is mentioned, but I would also add:
- In the documentation, add a comprehensive table of the precise and exact definitions of each climate indice. I thought this has always been missing, even though there is the pdf available for example for ECA&D. This will also help to be properly referenced in google for users to find the package.
- Bring examples up-to-date with new version (for example "index TG90p with callback" may not be relevant anymore).
- Reference the notebooks developed for C4I. And maybe have a Gallery of a few examples using those notebooks?
