### ISSUE TITLE
Simple test suite for ICCLIM

### ISSUE THREAD

**Issue by marev711** [cerfacs-globc/icclim#11]
Implement a simple test framework/script for simple system/regression tests of ICCLIM. Initial test cases would be, 
- Run a set of indices to produce output files without crashing 
- Compare produced output with reference data set, either from earlier tests or from independently generated indices. 

My initial idea is a simple test script with test cases defined in a separate file and to wrap it all up using the [Robot Framwork](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html)

**Comment by huard** [comment]
We've developed in [xclim](https://github.com/Ouranosinc/xclim) an xarray implementation of some of the ICCLIM indices and we'd like to compare results to make sure our implementation generates results comparable to ICCLIM. I was wondering what is the status of this issue, and could we eventually get access to such output files and reference data set for comparison.

**Comment by pagecp** [comment]
Hi David (@huard), I have seen your impressive xclim developments. The suite has been developed and was working, but that was with a previous version of icclim using python 2.7 at that time. I suspect those need to be updated to work with python 3.x. But this framework is quite good imho. I may have time before leaving for 2-weeks on Aug 15th to look at it.
