### ISSUE TITLE
Performance of existing bootstrap algorithm

### ISSUE THREAD

**Issue by marev711** [cerfacs-globc/icclim#14]
A discrepancy in the performance when running the bootstrap algorithm at has been reported and it would be good to pin down the exact cause. If it turns out to be related to the required amount of memory it would be good to get a rough idea how ICCLIM handles memory, e.g. if it simply scales with input file size.

**Comment by marev711** [comment]
ICCLIM performance has been probed with 

- ``kcachegrind``, see [https://wiki.python.org/moin/PythonSpeed/Profiling](https://wiki.python.org/moin/PythonSpeed/Profiling), to identify the ICCLIM ``dict`` handling to be a probable culprit in performance wrt memory management when listing a single file as input instead of a list of sub-files
- ``line_profiler``, see [https://github.com/rkern/line_profiler](https://github.com/rkern/line_profiler), has been used to probe timings in the percentile computation and significant amount of time (90+%) seems to be spent in the algorithm identifying the time window for each percentile, [line 284 in calc_percentile.py](https://github.com/cerfacs-globc/icclim/blob/master/icclim/calc_percentiles.py#L284)

**Comment by xpivan** [comment]
Hi,

The problem in the bootstrapping is due to overuse of loop instead of vectorizing. A new version should be pushed soon where the bootstrapping method is well vectorized, reducing to a factor ~40 the computing cost and so lighten greatly the memory.

**Comment by pagecp** [comment]
This is the xarray alpha version that implements this parallel execution.
