### ISSUE TITLE
Indicator calculation on KNMI EOBS files fails.

### ISSUE THREAD

**Issue by maartenplieger** [cerfacs-globc/icclim#18]
Calculating indicator SU on the following resource fails:

http://opendap.knmi.nl/knmi/thredds/dodsC/e-obs_0.25regular/tx_0.25deg_reg_v12.0.nc

This is an OpenDAP URL (use ncdump -h on URL).

**Comment by marev711** [comment]
Thanks for raising the issue! I've not managed to reproduce the error locally, could you specify under what conditions it fails? My test so far was to, 

**OpenDAP test** (only 2-year test to avoid download time)
> $ `python`
> `import icclim`
> `import datetime`
> `files=['http://opendap.knmi.nl/knmi/thredds/dodsC/e-obs_0.25regular/tx_0.25deg_reg_v12.0.nc']`
> `dt1=datetime.datetime(1990,1,1)`
> `dt2=datetime.datetime(1992,12,31)`
> `out_f = 'SU_JJA_E-OBS_observation-opendap_r1i1p1_1990-1992.nc'`
> `icclim.indice(indice_name='SU', in_files=files, var_name='tx', time_range=[dt1, dt2], transfer_limit_Mbytes=450.0, slice_mode='JJA', out_file=out_f)`

This works out and the output file looks ok from what I can tell.

**Comment by maartenplieger** [comment]
Thanks for the investigation! I just downloaded the latest master from this site.

The problem is that the result has zero summer days, while obviously temperature is above 25 degrees at some grid cells.

Note1: For other datasets this works fine
Note2: This file has scale and offset attributes....?

**Comment by maartenplieger** [comment]
Could it be units=Celsius, instead of Kelvin of the input file?

**Comment by pagecp** [comment]
I released V4.1.2 to correct this problem.
The auto-conversion from Celsius to Kelvin was not working correctly.

Christian

**Comment by maartenplieger** [comment]
Confirmed that this conversion is working correctly. Thanks for fixing.
