### ISSUE TITLE
For EUR-11 missing vars: x,y (as in rlon,rlat on EUR-44), rotated_pole and glob attributes 

### ISSUE THREAD

**Issue by igryski** [cerfacs-globc/icclim#20]
EUR-11 ensemble indices files are missing:
1. The variables x,y (analogue to rlon,rlat on EUR-44)
2. Variable rotated_pole

And the attribute grid_mapping: "rotated pole"

Seems this causes issues in adaguc visualization and quicklooks on climat4impact portal.

See 3 ensemble netcdf headers comparison here (from left to right 2deg, 0p5deg and 0p11deg):
![screenshot from 2016-05-09 12 12 45](https://cloud.githubusercontent.com/assets/7983626/15110118/647e7354-15df-11e6-8c5a-21b2c3285ea4.png)

**Comment by pagecp** [comment]
Could you send me the icclim call you are using for those 3 different results with, especially also, the input files so that I can do the tests to be able to fix them? 
Thanks!

**Comment by igryski** [comment]
Was a long while ago, i'm afraid the scripts for this output have been changed quite a bit. However, the call itself is not changed too much from:
icclim.indice(indice_name=indice_pp,
	    	     in_files=files_pr_50km,
	             var_name='prAdjust', 
               	     slice_mode='year',
        	     time_range=[dt1,dt2], 
           	     base_period_time_range=[base_dt1, base_dt2],
               	     out_file=out_indice_pp, 
                     callback=callback.defaultCallback2)
Input files were bias-corrected RCM CORDEX files on three resolutions: eur2deg, eur-44 and eur-11.

**Comment by xpivan** [comment]
Hi. 
I'm currently working on that issue. My netcdf header for eur-11 differs from yours and is as follow:

dimensions:
	time = UNLIMITED ; // (1 currently)
	y = 453 ;
	x = 453 ;
	bnds = 2 ;
variables:
	double time(time) ;
		time:standard_name = "time" ;
		time:units = "days since 1949-12-01" ;
		time:calendar = "gregorian" ;
		time:bounds = "time_bnds" ;
		time:axis = "T" ;
		time:long_name = "time" ;
	double y(y) ;
		y:units = "km" ;
		y:long_name = "y coordinate of projection" ;
		y:standard_name = "projection_y_coordinate" ;
		y:axis = "Y" ;
	double x(x) ;
		x:units = "km" ;
		x:long_name = "x coordinate of projection" ;
		x:standard_name = "projection_x_coordinate" ;
		x:axis = "X" ;
	double time_bnds(time, bnds) ;
		time_bnds:units = "days since 1949-12-01" ;
		time_bnds:calendar = "gregorian" ;
	double lat(y, x) ;
		lat:standard_name = "latitude" ;
		lat:long_name = "latitude" ;
		lat:units = "degrees_north" ;
	double lon(y, x) ;
		lon:standard_name = "longitude" ;
		lon:long_name = "longitude" ;
		lon:units = "degrees_east" ;
	char Lambert_Conformal ;
		Lambert_Conformal:grid_mapping_name = "lambert_conformal_conic" ;
		Lambert_Conformal:longitude_of_central_meridian = 10.5f ;
		Lambert_Conformal:standard_parallel = 49.5f ;
		Lambert_Conformal:latitude_of_projection_origin = 49.5f ;
	float RR1(time, y, x) ;
		RR1:_FillValue = 1.e+20f ;
		RR1:grid_mapping = "Lambert_Conformal" ;
		RR1:standard_name = "precipitation_flux" ;
		RR1:long_name = "Wet days (precipitation >= 1 mm)" ;
		RR1:units = "days" ;
		RR1:cell_methods = "time: mean" ;
		RR1:coordinates = "lat lon" ;
		RR1:missing_value = 1.e+20f ;

// global attributes:
		:title = "ECA rain indice RR1" ;
		:institution = "Climate impact portal (http://climate4impact.eu)" ;
		:source = "" ;
		:references = "ATBD of the ECA indices calculation (http://eca.knmi.nl/documents/atbd.pdf)" ;
		:comment = " " ;
		:history = " \n",
			"2018-10-10 14:25:52 Calculation of RR1 indice (autumn time series) from 1950-1-1 to 1950-12-31." ;
		:Conventions = "CF-1.6" ;
}

Let me know if my header would solve your problem.

Best regards
