### ISSUE TITLE
_FillValue turned to zero non-missing for the indices based on counting threshold e.g. WSDI

### ISSUE THREAD

**Issue by MilkaRadojevic** [cerfacs-globc/icclim#21]
In grid points with _FillValue, WSDI is set to zero instead of _FillValue.

**Comment by pagecp** [comment]
I have fixed it in the fillval branch. Still need to run the tests to be sure that I did not introduce any bug, since many modifications were needed into the code. It was not only for WSDI but also for other indices.

**Comment by pagecp** [comment]
Merged in master.
