### ISSUE TITLE
RX1Day using icclim-4.2.4: UnboundLocalError: local variable 'intersecting_years' referenced before assignment

### ISSUE THREAD

**Issue by armellereca** [cerfacs-globc/icclim#22]
Hallo, I tried to calculate the RX1DAY for evaluation period of REMO and CLM.  

**python script:**

indices = ['RX1DAY']
mode_of_slices = ['year']
models = ['MPI-CSC-REMO2009', 'CLMcom-CCLM4-8-17']
sim='EUR44'
inputdir=BASE+sim+'/daily/download/'+var+'/'
outdir='/work/m300021/highendex/indices/outclim/'

dt1 = datetime.datetime(1989,1,2)
dt2 = datetime.datetime(2008,12,31)

for index in indices:
    for model in models:
        for mode_of_slice in mode_of_slices:
            FILES = sorted(get_files(inputdir,'*ERAINT*'+model+'*'))
            print(index,FILES)
            os.chdir(inputdir)    
            out_f = outdir+index+'_'+mode_of_slice+'_'+sim+'_ECMWF-ERAINT_evaluation_r1i1p1_'+model+'_v1_day_1989-2008.nc'
            icclim.indice(indice_name=index, in_files=FILES, var_name=var, slice_mode=mode_of_slice, 
                          time_range=[dt1, dt2], out_file=out_f)

**python output:**

error: ('RX1DAY', ['pr_EUR-44_ECMWF-ERAINT_evaluation_r1i1p1_MPI-CSC-REMO2009_v1_day_19890102-19901231.nc', 'pr_EUR-44_ECMWF-ERAINT_evaluation_r1i1p1_MPI-CSC-REMO2009_v1_day_19910101-19951231.nc', 'pr_EUR-44_ECMWF-ERAINT_evaluation_r1i1p1_MPI-CSC-REMO2009_v1_day_19960101-20001231.nc', 'pr_EUR-44_ECMWF-ERAINT_evaluation_r1i1p1_MPI-CSC-REMO2009_v1_day_20010101-20051231.nc', 'pr_EUR-44_ECMWF-ERAINT_evaluation_r1i1p1_MPI-CSC-REMO2009_v1_day_20060101-20081231.nc'])

UnboundLocalError                         Traceback (most recent call last)
<ipython-input-19-5f1d314ff215> in <module>()
     16             out_f = outdir+index+'_'+mode_of_slice+'_'+sim+'_ECMWF-ERAINT_evaluation_r1i1p1_'+model+'_v1_day_1989-2008.nc'
     17             icclim.indice(indice_name=index, in_files=FILES, var_name=var, slice_mode=mode_of_slice, 
---> 18                           time_range=[dt1, dt2], out_file=out_f)

icclim-4.2.4-py2.7.egg/icclim/icclim.pyc in indice(in_files, var_name, indice_name, slice_mode, time_range, out_file, threshold, N_lev, transfer_limit_Mbytes, callback, callback_percentage_start_value, callback_percentage_total, base_period_time_range, window_width, only_leap_years, ignore_Feb29th, interpolation, out_unit, netcdf_version, user_indice)
    553                                                         ignore_Feb29th=ignore_Feb29th, interpolation=interpolation,
    554                                                         out_unit=out_unit,
--> 555                                                         user_indice=user_indice) ## tuple: (dt_centroid_arr, dt_bounds_arr, indice_arr) 
    556             indice_arr_current_chunk = indice_tuple_current_chunk[2]
    557 

icclim-4.2.4-py2.7.egg/icclim/icclim.pyc in get_indice_from_dict_temporal_slices(indice_name, vars_dict, thresh, window_width, only_leap_years, callback, callback_percentage_start_value, callback_percentage_total, ignore_Feb29th, interpolation, out_unit, user_indice)
    909 
    910             ### for out-of-base years
--> 911             if slice[1] not in intersecting_years: # slice[1] --> year
    912                 current_intersecting_year = -9999
    913                 reduced_base_years_list = [-9999]

UnboundLocalError: local variable 'intersecting_years' referenced before assignment

**Comment by pagecp** [comment]
Thanks for the report. I will work on it right now to fix it.

**Comment by pagecp** [comment]
Did you try to use instead RX1day as indice name? I tested using RX1DAY and I got the same error, while RX1day was working.
In the code (line 133, calc_ind.py) we can see that day is lowercase in the indice name.
I updated the master branch with a proper check of the indice name.
I will also update the documentation on readthedocs to be sure that implemented indice names are listed.

**Comment by pagecp** [comment]
Indice names are listed here: [http://icclim.readthedocs.io/en/latest/intro.html#what-is-a-climate-indice](http://icclim.readthedocs.io/en/latest/intro.html#what-is-a-climate-indice)

**Comment by armellereca** [comment]
thanks Christian! surprisingly, RX1DAY worked in some files before stopping.
and now, RX1day runs without stopping. Thanks!

**Comment by pagecp** [comment]
Great, nice to see that it now runs! Definitely prior results with RX1DAY are not ok... it was a good chance that you spotted the bug to prevent incorrect results with not defined indice name :)
