### ISSUE TITLE
Urgent: Only the latest documentation is available at http://icclim.readthedocs.org

### ISSUE THREAD

**Issue by MilkaRadojevic** [cerfacs-globc/icclim#25]
But we also need the access to previous documentation for the reference netcdf attribute. 

I am working on assigning Netcdf attribute values to a set of indices calculated by icclim310.
Can someone enable links to previous references?

Many thanks!

**Comment by pagecp** [comment]
It is available here: http://icclim.readthedocs.io/en/v3.1.0/ <http://icclim.readthedocs.io/en/v3.1.0/>

Christian
