### ISSUE TITLE
Python 3 compatibility?

### ISSUE THREAD

**Issue by bekozi** [cerfacs-globc/icclim#26]
`ocgis` is supporting Python 3.5+ in the next release. I naively tested against an `icclim` 4.2.5 version built with Python 3.6 and encountered issues. Does `icclim` have plans to support Python 3? Python 2.7 will still be supported in `ocgis`. I made an attempt to fix some of the basic syntax issues but received some errors deep in the calculation code which I couldn't parse easily.

**Comment by pagecp** [comment]
icclim will not be updated in the short term to support Python 3.5+, but I expect that starting in May I will have time to work on it.

**Comment by bekozi** [comment]
Thanks for the update @pagecp. I don't expect it will be too bad.

**Comment by pagecp** [comment]
There is a new python3 branch for icclim. It is not all fully-tested version yet, but it works for a few test files for now. I am working on this branch right now, so many git push are being done attm. Maybe you would like to test it.

**Comment by bekozi** [comment]
Nice! I will give it a go. What is the preferred method for running tests? I have not added this to the Anaconda build we use. Just execute https://github.com/cerfacs-globc/icclim/blob/master/icclim/test-cases/icclim-test-wrapper.py? Thanks!

**Comment by pagecp** [comment]
This was the initial test script, but one collaborator implemented the Robot Framework, in another branch, which I need to finalise the tests and merge.

=====
1) checkout the branch "pybot-testsuite" 
2) install the robot framework, e.g., "pip install robotframework" 
3) if necessary, update the "test-cases/default_variables.txt"-file (or at least link the input folder name so it is available in the root folder) 
4) execute "robot test-cases" and it should get going (note that if using any version prior to 3.0 of the framework the syntax is "pybot test-cases"). 

The "robot"-command recursively traverses the "test-cases/"-folder and executes all the test case files found, currently, 

* test-cases/test-cases-360-days/robot-360-days.txt 
* test-cases/test-cases-opendap/robot-opendap.txt 
* test-cases/test-cases-read-the-docs/robot-read-the-docs.txt 

As can be seen from these files the current test procedure is quite simple, simply execute and check the exit status, this could of course be changed if we want a more detailed criteria for test success, e.g., comparison of output files with earlier runs. Output from the running the tests is a summary to stdout + xml/html-files + text files with the test case "stdout_*", "stderr_*"
====

The icclim-test-wrapper.py can still be used, but the test data is not available anymore.

**Comment by bekozi** [comment]
My sincerest apologies for the delay on getting back to you on this. I have a quick PR to address a couple Python 3 build issues: https://github.com/cerfacs-globc/icclim/pull/32.

**Comment by pagecp** [comment]
Sorry for the delay, I was still on holidays. I merged the PR into the main branch, but I also included some changes in the netcdf3 branch.

**Comment by pagecp** [comment]
I think all issues are resolved now. Ben can you confirm?

**Comment by bekozi** [comment]
> Sorry for the delay, I was still on holidays.

No worries. I'm just jealous. :smile:

> I think all issues are resolved now. Ben can you confirm?

Clean on my end: https://travis-ci.org/NCPP/ocgis/jobs/350427172

We'll be hosting ICCLIM Python 2.7, 3.5, and 3.6 builds in the NESII Anaconda channel for Linux and OSX: https://anaconda.org/nesii/icclim

There is also going to be an OCGIS release in the next few weeks, and I'd like to point to the most recent ICCLIM version. Is it easy to tag a bug fix release with the Python 3 fixes?

**Comment by pagecp** [comment]
> 

Hi Ben!
> Sorry for the delay, I was still on holidays.
> 
> No worries. I'm just jealous. 😄
> 
> 
😊🙃

> I think all issues are resolved now. Ben can you confirm?
> 
> Clean on my end: https://travis-ci.org/NCPP/ocgis/jobs/350427172 <https://travis-ci.org/NCPP/ocgis/jobs/350427172>
> 
Nice!
> We'll be hosting ICCLIM Python 2.7, 3.5, and 3.6 builds in the NESII Anaconda channel for Linux and OSX: https://anaconda.org/nesii/icclim <https://anaconda.org/nesii/icclim>
> 
Great! :) :) 
> There is also going to be an OCGIS release in the next few weeks, and I'd like to point to the most recent ICCLIM version. Is it easy to tag a bug fix release with the Python 3 fixes?
> 
> 
Are you using the master branch or the netcdf3 branch? 
I will tag the proper one.

Christian

**Comment by bekozi** [comment]
> Are you using the master branch or the netcdf3 branch? I will tag the proper one.

I've been using the master branch. Would you recommend a different branch?

**Comment by pagecp** [comment]
I had made all the changes for python 3.6.x+ in the netcdf3 branch, but if you can already use the master branch with python3 you can stay with the master branch.

**Comment by bekozi** [comment]
Got it. Either branch is fine with me.

**Comment by pagecp** [comment]
ok let's go for the master branch, and I will tag it now

**Comment by bekozi** [comment]
👍 I'll close this issue too. Thank you!

**Comment by monobakht** [comment]
Sorry guys I know this issue is closed but I didn't want to open a new issue. I was just wondering, is Python 3 supported in the latest version of ICCLIM? @pagecp

**Comment by pagecp** [comment]
Hi,
The branch netcdf3 is python 3 supported, but the goal is to merge it with the default branch asap.
Some users have reported problems with python 3 on both netcdf3 and default branches, which I was not able to reproduce yet. 
Your experience could be valuable...
Christian
