### ISSUE TITLE
Preferred citation?

### ISSUE THREAD

**Issue by bschroeter** [cerfacs-globc/icclim#264]
Hi icclim developers,

We are using data processed through icclim for a journal submission and we'd like to acknowledge the software in the manuscript.

Do you have a preferred citation or DOI that you would like used for this?

Thanks in advance,

Ben Schroeter

**Comment by bzah** [comment]
Hi @bschroeter,
Thanks for your interest in icclim!

We have a Zenodo DOI: https://zenodo.org/record/7643964
If you want to cite a specific version, there are DOIs since 5.0.2: https://zenodo.org/search?page=1&size=20&q=conceptrecid:6046052&all_versions&sort=-version

**Comment by bschroeter** [comment]
@bzah, Thanks for the quick response. Much appreciated.
