### ISSUE TITLE
ENH: Automate release process to pipy/conda-forge

### ISSUE THREAD

**Issue by bzah** [cerfacs-globc/icclim#272]
* icclim version: 6.4.0
* Python version: n/a

### Description

We already have a very useful Continuous Integration pipeline that lints, tests, generates logos and generate a good chunk of the API.
The next step would be to automate the delivery process described in doc/source/dev/release_process.rst to avoid human mistake and ease deployment.
This seems especially important as some of our user may need a quick release after a new version of xclim is published (as #261 has revealed).

We could either make it fully autonomous and run the pipeline whenever the version number has been updated or, if we want more control, we could make it a [release the kraken](https://www.youtube.com/watch?v=38AYeNGjqg0&pp=ygUScmVsZWFzZSB0aGUga3Jha2Vu) button that we would manually trigger (not sure how to do that yet with github actions).

As a side note, we are always doing manually the release on conda-forge through icclim-feedstock, but if we are not in a hurry to have the release on both pipy and conda-forge, we can let conda-forge own automate process create the pull request on the feedstock. We would just have to review and merge it to make it a release.

**Comment by pagecp** [comment]
I agree very much that doing a release still involves manual process that is prone to potential errors and takes time. This would really ease the release process especially for quick updates because of critical dependencies updates.
