### ISSUE TITLE
Documentation -- netCDF4 version 1.2.9 required

### ISSUE THREAD

**Issue by larsbarring** [cerfacs-globc/icclim#28]
With netCDF4 version 1.2.7 icclim crashed for certain files:
    File "netCDF4/_netCDF4.pyx", line 4116, in netCDF4._netCDF4.Variable.__setitem__ (netCDF4/_netCDF4.c:47421)
    IndexError: in the future, 0-d boolean arrays will be interpreted as a valid boolean index

I was not able to pinpoint the exact cause of this error (neither in the file structure nor in the code). But the problem disappeared after upgrading to netCDF4 version 1.2.9. (see [netcdf4-python issue #521] (https://github.com/Unidata/netcdf4-python/issues/521)

It would be appropriate to state this version requirement in the dependencies section of the readthedocs documentation.

**Comment by pagecp** [comment]
Thanks to pointing that out. I have updated documentation to require netCDF4 1.2.9+
