### ISSUE TITLE
Release and tag 6.5.0 are missing

### ISSUE THREAD

**Issue by thebaptiste** [cerfacs-globc/icclim#290]
Hello

Your new release 6.5.0 is available on pypi, great !
But the corresponding tag and release (with the changelog) are missing on github.

Best regards

**Comment by bzah** [comment]
Hi @thebaptiste
Thanks I forgot to do it after the conda release.
It's now done, see https://github.com/cerfacs-globc/icclim/releases/tag/v6.5.0

Cheers
