### ISSUE TITLE
AttributeError in the indice function

### ISSUE THREAD

**Issue by pauliscuss** [cerfacs-globc/icclim#30]
I am relatively new to python so may be overlooking something quite obvious (apologies in that case), but no matter what input nc file I use, when calling the icclim.indice function, it 'begins execution' and the immediately raises an
`AttributeError: NetCDF: Attribute not found`
It gets stuck in the icclim.py file at
`line 245, in indice
    fill_val = ncVar._FillValue.astype('float32') # fill_value must be the same type as "ind_type", i.e. 'float32'`
`File "netCDF4/_netCDF4.pyx", line 3913, in netCDF4._netCDF4.Variable.__getattr__
 File "netCDF4/_netCDF4.pyx", line 3724, in netCDF4._netCDF4.Variable.getncattr
 File "netCDF4/_netCDF4.pyx", line 1188, in netCDF4._netCDF4._get_att
 File "netCDF4/_netCDF4.pyx", line 1638, in netCDF4._netCDF4._ensure_nc_success`
I call the function this way:
`icclim.indice(in_files=ncfile_LIG, var_name='PRECT', out_file=out_file, indice_name='RX5day', slice_mode='year', callback = callback.defaultCallback)`
The input nc files I tried are fine for all other purposes. I guess there's something wrong with the fill value of (all) my variables (type: float32), but can't seem to find a solution.
Could you assist please?

**Comment by larsbarring** [comment]
Could you provide the output from a 
`ncdump -h` _file_
of the header information of a _file_ that cause this error.

**Comment by pauliscuss** [comment]
Thanks for replying fast! Sure, here you go:
`netcdf PRECT_NBF1850OC_f19_tn11_01_127ka_paolo.cam2.h1.1701-1702 {
dimensions:
	time = UNLIMITED ; // (365 currently)
	lat = 96 ;
	lon = 144 ;
	nbnd = 2 ;
variables:
	float PRECT(time, lat, lon) ;
		PRECT:units = "m/s" ;
		PRECT:long_name = "Total (convective and large-scale) precipitation rate (liq + ice)" ;
		PRECT:cell_methods = "time: mean" ;
	double lat(lat) ;
		lat:units = "degrees_north" ;
		lat:long_name = "latitude" ;
	double lon(lon) ;
		lon:units = "degrees_east" ;
		lon:long_name = "longitude" ;
	double time(time) ;
		time:units = "days since 0001-01-01 00:00:00" ;
		time:long_name = "time" ;
		time:calendar = "noleap" ;
		time:bounds = "time_bnds" ;
	double time_bnds(time, nbnd) ;
		time_bnds:long_name = "time interval endpoints" ;
}`

**Comment by larsbarring** [comment]
Just to reformat:

```
netcdf PRECT_NBF1850OC_f19_tn11_01_127ka_paolo.cam2.h1.1701-1702 { 
dimensions: 
   time = UNLIMITED ; // (365 currently) 
   lat = 96 ; 
   lon = 144 ; 
   nbnd = 2 ; 
variables: 
   float PRECT(time, lat, lon) ; 
      PRECT:units = "m/s" ; 
      PRECT:long_name = "Total (convective and large-scale) precipitation rate (liq + ice)" ; 
      PRECT:cell_methods = "time: mean" ; 
   double lat(lat) ; 
      lat:units = "degrees_north" ; 
      lat:long_name = "latitude" ; 
   double lon(lon) ; 
      lon:units = "degrees_east" ; 
      lon:long_name = "longitude" ; 
   double time(time) ; 
      time:units = "days since 0001-01-01 00:00:00" ; 
      time:long_name = "time" ; 
      time:calendar = "noleap" ; 
      time:bounds = "time_bnds" ; 
   double time_bnds(time, nbnd) ; 
      time_bnds:long_name = "time interval endpoints" ; 
}
```

**Comment by larsbarring** [comment]
Are you using the latest release, **4.2.9**? If not please try this and report back if you still encounter the problem.

**Comment by pauliscuss** [comment]
I update the package to 4.2.9 and I don't get the error anymore.
Please notice that in Anaconda the package is still 4.2.5
Thank you so much!
