### ISSUE TITLE
icclim doesn't support NetCDF4/HDF5 from CMIP6 as reported

### ISSUE THREAD

**Issue by MilkaRadojevic** [cerfacs-globc/icclim#33]
Does anyone has an exprience with running icclim on the new set of CMIP6 simulations?
Laurent Terray (Cerfacs) runs them on the CEDA's jasmin server. It seams more as a compatibility issue in compilation with netcdf4/hdf5 lib.

Any thoughts on this?

Many thanks, Milka
ps
Yes, I am back :)

**Comment by pagecp** [comment]
Processing CMIP6 data has been tested and now works as expected.
