### ISSUE TITLE
2D Lat/Lon coordinates not supported

### ISSUE THREAD

**Issue by MilkaRadojevic** [cerfacs-globc/icclim#35]
As reported, the icclim does not support when the input file contains spatial coordinates in 2D.
Since the icclim approach is based on processing data values over time for each grid point (station), the grid characteristics are only loaded and then rewritten to an output file. Therefore, this should be an easy fix.

Since the CMIP6 output is getting ready and the icclim is starting to be used for this purpose, we should make sure that the icclim supports fully those files.

**Comment by bzah** [comment]
Icclim 5.0.0 is able to handle 2D spatial coordinate, thus I'm closing this issue.
Feel free to reopen if you think this is still an issue.
