### ISSUE TITLE
ICCLIM does not work with python netcdf library ^1.4.0

### ISSUE THREAD

**Issue by maartenplieger** [cerfacs-globc/icclim#38]
Hi,

It seems that icclim does not work with the latest python netcdf library. I was able to get it working with version 1.3.1 (pip install netcdf4==1.3.1)

It seems that the line 
```
import netcdftime
```
does not work with higher python netcdf4 versions than 1.3.1

Cheers,
Maarten

**Comment by xpivan** [comment]
Hi,

What kind of problem did you have ?

Cheers,
Xavier

**Comment by pagecp** [comment]
Fixed in the latest releases.
