### ISSUE TITLE
Can't use NETCDF4 (HDF5) files as input even if there is only one input file

### ISSUE THREAD

**Issue by jackaranda** [cerfacs-globc/icclim#75]
A number of points in the code use MFDataset to open multiple input files as one dataset.  However MFDataset doesn't support NETCDF4 files.  It would be great to revert to just using Dataset to open files if there is only one input file.  I'm aware things might change with the shift using xarray, but in the interim this is useful functionality.

**Comment by pagecp** [comment]
Yes this is a good fix! Will validate the merge request later today.

**Comment by bzah** [comment]
Closing. With icclim 5.0.0 we are now fully relying on xarray to open files so NETCDF4 should work naturally.
