### ISSUE TITLE
Bug in calling CWD_calculation in calc_ind.py

### ISSUE THREAD

**Issue by jackaranda** [cerfacs-globc/icclim#77]
The call to CWD_calculation is missing the module reference.

res =CWD_calculation(**kwargs)

should be:

res =calc_indice.CWD_calculation(**kwargs)

**Comment by pagecp** [comment]
Yes you are right, because of a change in imports this had not been updated properly.

**Comment by pagecp** [comment]
Fixed in 4.2.19.
